services:
  cassandra:
    image: cassandra:5.0-rc1
    container_name: cassandra-container
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  redis:
    image: redis:7.4
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

volumes:
  cassandra-data:
