networks:
  pipe-net:
    name: pipe-net
    driver: bridge

volumes:
  cassandra-data:

services:
  cassandra:
    image: cassandra:5.0-rc1
    container_name: cassandra-db
    networks:
      - pipe-net
    ports:
      - "127.0.0.1:9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      MAX_HEAP_SIZE: 4G
      HEAP_NEWSIZE: 800M
      CASSANDRA_USER: admin
      CASSANDRA_PASSWORD: admin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 6g
        reservations:
          memory: 4g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-init:
    image: cassandra:5.0-rc1
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init-cassandra.cql
    entrypoint: ["/bin/sh", "-c", "until cqlsh cassandra-db -e 'DESCRIBE KEYSPACES'; do sleep 10; done && cqlsh cassandra-db -f /docker-entrypoint-initdb.d/init-cassandra.cql"]
    networks:
      - pipe-net

  redis:
    image: redis:7.4
    container_name: redis-server
    networks:
      - pipe-net
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  pipe-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipe
    container_name: pipe-server
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    restart: always
    networks:
      - pipe-net
    volumes:
      - ./assets:/app/assets
    ports:
      - "127.0.0.1:1323:1323"
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - TOKEN=${TOKEN}
      - SERVER_ADDR=${SERVER_ADDR}
      - CLIENT_URL=${CLIENT_URL}
      - PROXY_ADDR=${PROXY_ADDR}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 1.5g
        reservations:
          memory: 1g
